# Generated by Django 6.1.1 on 2026-09-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('VOLUNTEER', 'Volunteer'), ('OFFICER', 'Officer'), ('ORGANIZATION', 'Organization'), ('ADMIN', 'Admin')], default='CITIZEN', max_length=20),
        ),
    ]
