# Generated by Django 6.1.1 on 2026-10-07 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_type', models.CharField(choices=[('COOKED_FOOD', 'Cooked Food'), ('PACKAGED_FOOD', 'Packaged Food'), ('GROCERIES', 'Groceries'), ('OTHER', 'Other')], max_length=30)),
                ('quantity', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('available_from', models.DateTimeField()),
                ('available_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COLLECTED', 'Collected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
