# Generated by Django 6.1.1 on 2026-10-07 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_fooddonation_accepted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('CLOTHES', 'Clothes'), ('BOOKS', 'Books'), ('FURNITURE', 'Furniture'), ('SCHOOL_ITEMS', 'School Items'), ('OTHER', 'Other')], max_length=30)),
                ('quantity', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('available_from', models.DateTimeField()),
                ('available_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COLLECTED', 'Collected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_item_donations', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
