# Generated by Django 6.1.1 on 2026-10-06 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_bloodvolunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to='blood.bloodvolunteer'),
        ),
    ]
