# Generated by Django 6.1.1 on 2026-09-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_assigned_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
