# Generated by Django 6.1.1 on 2026-09-30 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_remove_complaint_updated_at_complaint_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_complaints', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
