# Generated by Django 6.1.1 on 2026-09-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_duplicate_of_complaint_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='citizen_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
